### ISSUE TITLE
Always uses CURL

### ISSUE THREAD

**Issue by Lewiscowles1986** [imiskolee/FormUpload#1]
would be nice to have an interface so CURL could be swapped out in-future.

This basically only needs a header, a request body and a url. curl_init, all that jazz should just be passed to the constructor or the method that uses, so if needed someone could swap out for socket implementation or alternative HTTP client.

That way all this is concerned with is providing an API for the upload. The transport and delivery can be handled by existing libs. Saves you time & Effort, and reduces the bugs you could be asked to address.

**Comment by imiskolee** [comment]
tks！ good idea。

**Comment by Lewiscowles1986** [comment]
want a PR?

**Comment by imiskolee** [comment]
@Lewiscowles1986  Yeah, u can PR it.

**Comment by Lewiscowles1986** [comment]
Right I've started here https://github.com/Lewiscowles1986/FormUpload/tree/re-factor

I Just need to test the output, and then maybe I'll create a dev requirement for Guzzle so I can check it works. (probably an idea)

I've also created a unit-test suite. It would be a nice idea to have tests for each entry in the RFC at a future date.

**Comment by Lewiscowles1986** [comment]
I've gone from a fork & PR to a split. Sorry, there was too much to fix once I sat with the RFC
