### ISSUE TITLE
doesn't support multiple file input with same name

### ISSUE THREAD

**Issue by Lewiscowles1986** [imiskolee/FormUpload#2]
From the [RFC Document](https://www.rfc-editor.org/rfc/rfc1867.txt) similar output to this is required (the boundary is likely random noise) 
```
content-type: multipart/form-data, boundary=--B6D6B1BD7A5621C1

--B6D6B1BD7A5621C1
content-disposition: form-data; name="submitter"

Joe Blow
--B6D6B1BD7A5621C1
content-disposition: form-data; name="pics"
content-type: multipart/mixed, boundary=--04DFE55F150396BE

--04DFE55F150396BE
content-disposition: attachment; filename="file1.txt"
content-type: text/plain

...contents of file1.txt...
--04DFE55F150396BE
content-disposition: attachment; filename="file2.gif"
content-type: image/gif
content-transfer-encoding: binary

...contents of file2.gif...
--04DFE55F150396BE--
--B6D6B1BD7A5621C1--
```

The library as-is doesn't support this and would likely require a deep structure to do so.

**Comment by Lewiscowles1986** [comment]
The way I tackled this was to implement an envelope. By the time I was done on that, no original code remained, so I decided to just split the repo.

**Comment by imiskolee** [comment]
@Lewiscowles1986  i will be close this project, and redirect to https://github.com/Lewiscowles1986/rfc1867, its best then me.

**Comment by Lewiscowles1986** [comment]
Sorry, that's not what I was saying. It just didn't feel right to basically start afresh, and then bolt it all into this.

**Comment by imiskolee** [comment]
@Lewiscowles1986  i see! u can pr this if u want.

**Comment by Lewiscowles1986** [comment]
You can pull if you like, but I've abandoned the fork as it has a design issue. (Essentially I worked out that embedded Envelope's with entries of their own require their own boundary and it was just a rewrite at that stage). TBH I came after you posted on Reddit, I love seeing what others post, seeing if I can add anything, and it seemed others had mentioned CURL etc. The problem is to go from "works", to "has automated tests", "dependencies can be switched", I felt there was nothing left of the original and then it's like kicking over someone's sandcastle.
